apiVersion: v1
kind: ReplicationController #Will be replaced by ReplicaSet
metadata:
   name: myapp-rc
   labels:
      app: myapp
      type: front-end

spec:
   template:
      metadata:
         name: nginx-pod
         labels:
            app: nginx-app
            type: front-end
      spec:
         containers:
           - name: nginx-container
             image: nginx
   replicas: 3